[influxdb_api]
url = 'http://127.0.0.1:8086'
token = 'jYRq3Qgtk6YarmeE6CZmpdPM3Rk4PF1FjlvMbs-SyXc6ubCkEODlCrkiTVKopYDkrohbe9PRT8Qtgx1iNXcP5w=='
org_name = 'main'

[grafana_api]
url = 'http://127.0.0.1:3000'
username = 'admin'
password = 'wsadwsad'
org_name = 'Main Org.'
influxdb_source_name = 'influxdb'

[receiver_server]
host = '0.0.0.0'
port = 5123
debug = true
