# Generated by Django 5.1.6 on 2025-03-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='id_in_project',
            field=models.IntegerField(),
        ),
    ]
