# Generated by Django 5.1.2 on 2024-11-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='current_db_file_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
