# Generated by Django 5.1.2 on 2024-11-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_center', '0002_alter_sensor_current_db_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_with_this_measurement', to='control_center.measurement'),
        ),
    ]
